---
- name: Install dependencies for python project
  become: yes
  hosts: all
  tasks:
    - name: Install pip package
      apt:
        name:
          - python3-pip
          - python3-setuptools
          - python3-dev
          - build-essential
          - python3-pip
          - python3-mysqldb
          - mysql-server
          - mysql-client
        state: present
    - name: Start mysql
      systemd:
        name: mysql
        state: started
    - name: Install bottle python package
      pip:
        name:
          - flask
          - flask-mysql
