---
- name: Install dependencies for python project
  become: yes
  hosts: all
  tasks:
    - name: Install pip package
      apt:
        name:
          - python3-pip
          - python3-setuptools
          - python3-dev
          - build-essential
          - python3-pip
          - python3-mysqldb
          - mysql-server
          - mysql-client
        state: present
    - name: Start mysql
      systemd:
        name: mysql
        state: started
    - name: Install pip python package
      pip:
        name:
          - flask
          - flask-mysql
    - name: Create database user with name 'db_user' and password 'Passw0rd' with all database privileges
      community.mysql.mysql_user:
        login_user: root
        login_password: password
        name: db_user
        password: Passw0rd
        priv: "*.*:ALL"
        state: present
    - name: Create a new database with name 'employee_db'
      community.mysql.mysql_db:
        login_user: root
        login_password: password
        name: employee_db
        state: present
    - name: Run several insert queries against db test_db in single transaction
      community.mysql.mysql_query:
        login_user: root
        login_password: password
        login_db: employee_db
        query:
          - CREATE TABLE employees (name VARCHAR(20))
          - INSERT INTO employees VALUES ('JOHN')
